version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: weather_forecast
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: .
    restart: 'no'
    command: yarn test
    ports:
      - 3000:3000
    volumes:
      - ./settings.json:/app/settings.json
    env_file:
      - .env
    links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo_data:
